"""auto migration

Revision ID: 69ca0a20a19c
Revises: 82ebd52b446b
Create Date: 2025-04-11 08:05:50.526423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "69ca0a20a19c"
down_revision: Union[str, None] = "82ebd52b446b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processing",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cultivate", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity_kg", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_processing_state"), "processing", ["state"], unique=False)
    op.create_index(op.f("ix_processing_year"), "processing", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processing_year"), table_name="processing")
    op.drop_index(op.f("ix_processing_state"), table_name="processing")
    op.drop_table("processing")
    # ### end Alembic commands ###
