"""add_category_and_qtd_ltrs_as_integer

Revision ID: 82cb688dd592
Revises: b9f2adf5bdd1
Create Date: 2025-05-25 15:52:18.963998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82cb688dd592'
down_revision: Union[str, None] = 'b9f2adf5bdd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('production', 'quantity_liters',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_production_category'), 'production', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_category'), table_name='production')
    op.alter_column('production', 'quantity_liters',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('production', 'category')
    # ### end Alembic commands ###
