"""auto migration

Revision ID: 82ebd52b446b
Revises:
Create Date: 2025-04-10 23:22:06.175647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "82ebd52b446b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "production",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("product", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity_liters", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_production_product"), "production", ["product"], unique=False
    )
    op.create_index(op.f("ix_production_year"), "production", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_production_year"), table_name="production")
    op.drop_index(op.f("ix_production_product"), table_name="production")
    op.drop_table("production")
    # ### end Alembic commands ###
