"""auto migration

Revision ID: 9be95e6ddd1a
Revises: 9613ab259c68
Create Date: 2025-04-26 12:29:13.484700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9be95e6ddd1a'
down_revision: Union[str, None] = '9613ab259c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importation',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importation_country'), 'importation', ['country'], unique=False)
    op.create_index(op.f('ix_importation_path'), 'importation', ['path'], unique=False)
    op.create_index(op.f('ix_importation_year'), 'importation', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_importation_year'), table_name='importation')
    op.drop_index(op.f('ix_importation_path'), table_name='importation')
    op.drop_index(op.f('ix_importation_country'), table_name='importation')
    op.drop_table('importation')
    # ### end Alembic commands ###
