"""auto migration

Revision ID: b9127e78dae4
Revises: 82cb688dd592
Create Date: 2025-05-25 22:15:32.047249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9127e78dae4'
down_revision: Union[str, None] = '82cb688dd592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('processing', sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('processing', 'quantity_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ix_processing_path', table_name='processing')
    op.create_index(op.f('ix_processing_category'), 'processing', ['category'], unique=False)
    op.create_index(op.f('ix_processing_subcategory'), 'processing', ['subcategory'], unique=False)
    op.drop_column('processing', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_processing_subcategory'), table_name='processing')
    op.drop_index(op.f('ix_processing_category'), table_name='processing')
    op.create_index('ix_processing_path', 'processing', ['path'], unique=False)
    op.alter_column('processing', 'quantity_kg',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('processing', 'subcategory')
    op.drop_column('processing', 'category')
    # ### end Alembic commands ###
