"""add commercialization table

Revision ID: bb602ca1d347
Revises: 82ebd52b446b
Create Date: 2025-04-11 15:10:07.396441

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "bb602ca1d347"
down_revision: Union[str, None] = "82ebd52b446b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commercialization",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("product", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity_liters", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_commercialization_product"),
        "commercialization",
        ["product"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commercialization_year"), "commercialization", ["year"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_commercialization_year"), table_name="commercialization")
    op.drop_index(op.f("ix_commercialization_product"), table_name="commercialization")
    op.drop_table("commercialization")
    # ### end Alembic commands ###
