"""auto migration

Revision ID: d21370a9db93
Revises: 9be95e6ddd1a
Create Date: 2025-04-28 21:38:25.185578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d21370a9db93"
down_revision: Union[str, None] = "9be95e6ddd1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("importation", "value")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("importation", sa.Column("value", sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
