"""auto migration

Revision ID: e2f799be3349
Revises: c3ebb90bbb95
Create Date: 2025-04-15 08:53:16.139644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2f799be3349'
down_revision: Union[str, None] = 'c3ebb90bbb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing', sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_processing_path'), 'processing', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_path'), table_name='processing')
    op.drop_column('processing', 'path')
    # ### end Alembic commands ###
