"""auto migration

Revision ID: f13b9cae6f05
Revises: 4c2b25f97975
Create Date: 2025-05-31 00:50:26.383706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f13b9cae6f05"
down_revision: Union[str, None] = "4c2b25f97975"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the importation_category enum type first
    importation_category_enum = postgresql.ENUM(
        "VINHOS", "ESPUMANTES", "FRESCAS", "PASSAS", "SUCO", name="importation_category"
    )
    importation_category_enum.create(op.get_bind())

    op.add_column(
        "importation", sa.Column("category", importation_category_enum, nullable=False)
    )
    op.drop_index("ix_importation_path", table_name="importation")
    op.create_index(
        op.f("ix_importation_category"), "importation", ["category"], unique=False
    )
    op.drop_column("importation", "path")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "importation",
        sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_importation_category"), table_name="importation")
    op.create_index("ix_importation_path", "importation", ["path"], unique=False)
    op.drop_column("importation", "category")

    # Drop the importation_category enum type
    importation_category_enum = postgresql.ENUM(name="importation_category")
    importation_category_enum.drop(op.get_bind())
    # ### end Alembic commands ###
