"""add_none_to_processing_subcategory_enum

Revision ID: fb10734a49eb
Revises: 9b490aa122eb
Create Date: 2025-05-31 02:25:24.841479

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fb10734a49eb'
down_revision: Union[str, None] = '9b490aa122eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only modify the processing subcategory enum to add NONE value
    op.execute("ALTER TYPE processing_subcategory ADD VALUE 'NONE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove NONE value from processing subcategory enum
    # Note: PostgreSQL doesn't support removing enum values directly
    # This would require recreating the enum type which is complex
    pass
    # ### end Alembic commands ###
